_BASE_: "../coco/panoptic-segmentation/maskformer2_R50_bs16_50ep.yaml"

MODEL:
  WEIGHTS: "/workspace/checkpoints/dinov2_vitb14_pretrain.pth"
  SEM_SEG_HEAD:
    NUM_CLASSES: 15

DATASETS:
  TRAIN: ("drone_panoptic_train",)
  TEST:  ("drone_panoptic_val",)

DATALOADER:
  NUM_WORKERS: 8
  FILTER_EMPTY_ANNOTATIONS: True

INPUT:
  IMAGE_SIZE: 1024
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0

SOLVER:
  AMP:
    ENABLED: True
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  MAX_ITER: 93750
  WARMUP_ITERS: 10
  STEPS: (83333, 90277)
  GAMMA: 0.1
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  WEIGHT_DECAY: 0.05

TEST:
  EVAL_PERIOD: 5000

OUTPUT_DIR: "/workspace/output/drone_1024"
